### ISSUE TITLE
LLMプロバイダーと通知システムの抽象化によるローカル開発環境の改善

### ISSUE THREAD

**Issue by skanehira** [team-mirai-volunteer/fact-checker#38]
# LLMプロバイダーと通知システムの抽象化によるローカル開発環境の改善

## 背景

現在のfact-checkerは、OpenAI APIとSlack APIに強く依存しており、ローカル開発時に以下の課題があります：

- OpenAI APIキーが必須（コストが発生）
- Slack Bot設定が必須（セットアップが複雑）
- 環境変数が各モジュールに散在
- 外部サービスとビジネスロジックが密結合

#### LLMプロバイダーの抽象化
```typescript
interface LLMProvider {
  factCheck(content: string, vectorStoreId?: string): Promise<FactCheckResult>;
}
```

**実装候補：**
- OpenAIProvider（本番環境）
- LlamaProvider（ローカル/オンプレミス環境）
- MockProvider（開発/テスト環境）

#### 通知システムの抽象化
```typescript
interface Notifier {
  sendMessage(message: NotificationMessage): Promise<void>;
  handleInteraction(interaction: Interaction): Promise<void>;
}
```

**実装候補：**
- SlackNotifier（本番環境）
- ConsoleNotifier（開発環境）
- WebhookNotifier（汎用）

### 2. 設定管理の改善

環境別の設定ファイルを導入：
```yaml
# config/development.yml
env: development
llm:
  provider: mock  # または llama
notifier:
  provider: console

# config/production.yml
env: production
llm:
  provider: openai
notifier:
  provider: slack
```

#### オプション1: モックプロバイダー
- **メリット**: セットアップ不要、高速、無料
- **デメリット**: 実際のAI処理なし
- **用途**: UI開発、統合テスト

#### オプション2: Llama + LlamaIndex
- **メリット**: 完全ローカル実行、無料、データプライバシー
- **デメリット**: GPU必要、初期設定が複雑、日本語性能に課題
- **用途**: 本格的なローカル開発、オンプレミス要件

## 期待される効果

1. **開発効率の向上**
   - APIキーなしでローカル開発可能
   - 新規開発者のオンボーディング簡素化

2. **テストの改善**
   - モックを使った単体テストの実装が容易
   - 外部サービスに依存しないテスト実行

3. **柔軟性の向上**
   - 新しいLLMプロバイダーの追加が容易
   - 通知先の変更が設定のみで可能

4. **コスト削減**
   - 開発時のAPI利用料金削減
   - オンプレミス環境への対応可能
